SELECT ID AS PROJECT_ID, TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) AS MONTH_COUNT
FROM megasoft.project
WHERE TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) = (
    SELECT MAX(TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE))
    FROM megasoft.project
);
